import React from 'react';
import { Card } from '../Common/Card';
import { Sparkles, Lightbulb } from 'lucide-react';

interface InsightsProps {
  insights: string;
}

export const Insights: React.FC<InsightsProps> = ({ insights }) => {
  return (
    <Card
      title="Executive Query Insights & Summary"
      subtitle="Automated AI takeaway generated by SAP AI Core"
      action={
        <div className="p-1.5 bg-indigo-50 text-indigo-600 rounded-lg">
          <Sparkles className="w-4 h-4" />
        </div>
      }
    >
      <div className="p-4 bg-indigo-50/60 border border-indigo-100 rounded-xl text-xs sm:text-sm text-indigo-950 leading-relaxed font-medium">
        <div className="flex items-center gap-1.5 font-bold text-indigo-800 mb-2">
          <Lightbulb className="w-4 h-4 text-indigo-600" />
          <span className="uppercase tracking-wider text-[11px]">Key Findings</span>
        </div>
        <p className="whitespace-pre-wrap">{insights}</p>
      </div>
    </Card>
  );
};
