import React, { useState } from 'react';

interface ReportsLibraryProps {
  onNavigate: (path: string) => void;
}

export const ReportsLibrary: React.FC<ReportsLibraryProps> = ({ onNavigate }) => {
  const [reports] = useState([
    {
      id: 'rep-1',
      title: 'FY2024 Executive Sales Performance & Attainment Deck',
      type: 'Executive Board Deck',
      period: 'Annual 2024',
      format: 'PDF · 24 Pages',
      generatedDate: 'Jan 15, 2025',
      size: '14.2 MB',
    },
    {
      id: 'rep-2',
      title: 'Q3 2024 S/4HANA Go-Live Post-Mortem & Revenue Drift',
      type: 'Operational Audit',
      period: 'Q3 2024',
      format: 'Excel / CSV Workbook',
      generatedDate: 'Nov 02, 2024',
      size: '8.6 MB',
    },
    {
      id: 'rep-3',
      title: 'Regional Margin Elasticity & Sovereign Pricing Report',
      type: 'Financial Analytics',
      period: 'Monthly (Rolling)',
      format: 'PDF · 12 Pages',
      generatedDate: 'Feb 10, 2025',
      size: '5.1 MB',
    },
    {
      id: 'rep-4',
      title: 'Material Master SKU Leaderboard & Inventory Flow Analysis',
      type: 'Supply Chain',
      period: 'Bi-Weekly',
      format: 'Excel Workbook',
      generatedDate: 'Feb 22, 2025',
      size: '18.4 MB',
    },
  ]);

  const [downloadingId, setDownloadingId] = useState<string | null>(null);

  const handleDownload = (id: string, title: string) => {
    setDownloadingId(id);
    setTimeout(() => {
      setDownloadingId(null);
      const content = `Report Title: ${title}\nGenerated by: NEOVATIC GEN-AI - SAP HANA Cloud\nDate: ${new Date().toISOString()}\nStatus: Verified Compliant Tier-1 Audit`;
      const blob = new Blob([content], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${title.slice(0, 28).replace(/[^a-zA-Z0-9]/g, '_')}.txt`;
      a.click();
      URL.revokeObjectURL(url);
    }, 600);
  };

  return (
    <div className="flex flex-col w-full gap-space-xl">
      <div className="flex flex-col md:flex-row md:items-end justify-between gap-space-md">
        <div>
          <div className="flex items-center gap-2 mb-2">
            <span className="w-1.5 h-1.5 rounded-full bg-[#2563EB]"></span>
            <span className="font-label-sm uppercase tracking-widest text-[#64748B] font-semibold">
              ENTERPRISE REPORTING · SAP BTP DISPATCH
            </span>
          </div>
          <h1 className="font-headline-xl text-[#0F172A] font-semibold tracking-tight">
            Reports Library
          </h1>
          <p className="font-body-md text-[#475569] mt-1">
            Certified fiscal reports, automated board decks, and compliance exports generated from the HANA Column Store.
          </p>
        </div>

        <div className="flex items-center gap-2 shrink-0 self-start md:self-end mt-2 md:mt-0">
          <button 
            onClick={() => onNavigate('build-your-kpi-graph-studio')}
            className="inline-flex items-center justify-center gap-1.5 h-9 px-4 rounded-xl bg-white text-[#0F172A] font-label-md text-label-md hover:bg-[#F1F5F9] transition-colors shadow-xs border border-[#CBD5E1] whitespace-nowrap shrink-0"
          >
            <span className="material-symbols-outlined text-[16px] text-[#2563EB]">add</span>
            <span>Create New Report</span>
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-space-md">
        {reports.map((rep) => (
          <div 
            key={rep.id}
            className="bg-white p-6 rounded-2xl shadow-xs border border-[#E2E8F0] flex flex-col justify-between hover:border-[#CBD5E1] transition-all"
          >
            <div>
              <div className="flex items-center justify-between mb-2">
                <span className="text-xs font-semibold uppercase tracking-wider text-[#64748B]">
                  {rep.type}
                </span>
                <span className="text-xs font-mono text-[#64748B] bg-[#F1F5F9] px-2 py-0.5 rounded-md border border-[#E2E8F0]">{rep.period}</span>
              </div>
              <h3 className="font-headline-sm font-semibold text-[#0F172A] mb-2">
                {rep.title}
              </h3>
              <div className="flex items-center gap-3 text-xs text-[#64748B] mb-4">
                <span>{rep.format}</span>
                <span>•</span>
                <span>{rep.size}</span>
                <span>•</span>
                <span>Issued {rep.generatedDate}</span>
              </div>
            </div>

            <div className="pt-4 border-t border-[#E2E8F0] flex items-center justify-between">
              <span className="text-xs font-medium text-[#15803D] bg-[#DCFCE7] border border-[#BBF7D0] px-2.5 py-0.5 rounded-full flex items-center gap-1">
                <span className="material-symbols-outlined text-[13px] text-[#16A34A]">verified</span>
                Audit Signed
              </span>
              <button 
                onClick={() => handleDownload(rep.id, rep.title)}
                disabled={downloadingId === rep.id}
                className="px-4 py-1.5 rounded-xl bg-[#F8FAFC] hover:bg-[#F1F5F9] text-[#0F172A] border border-[#E2E8F0] text-xs font-medium transition-colors flex items-center gap-1.5"
              >
                <span className={`material-symbols-outlined text-[16px] text-[#2563EB] ${downloadingId === rep.id ? 'animate-spin' : ''}`}>
                  {downloadingId === rep.id ? 'refresh' : 'download'}
                </span>
                <span>{downloadingId === rep.id ? 'Exporting...' : 'Download'}</span>
              </button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};
